name: Flutter CI

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with: { flutter-version: '3.35.5' }
      - run: flutter pub get
      - run: flutter analyze lib --no-fatal-infos --no-fatal-warnings

  build_android:
    if: github.event_name == 'pull_request'
    needs: analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with: { flutter-version: '3.35.5' }
      - name: Accept Android licenses and install SDK 35
        run: |
          yes | sudo ${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager --licenses
          sudo ${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager \
            "platforms;android-35" "build-tools;35.0.0" --install
      - run: flutter pub get
      - run: flutter build apk --debug
